### PR TITLE
Update cookbook gallery

### LINKED ISSUE #68: Update Gallery with new Cookbook
### Root Repository Name

intake-cookbook

### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?

yes

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by jukent**
Update cookbook gallery as requested in #68. Closes #68.

### CODE REVIEW

**Review by kmpaul — APPROVED** [review]
Looks like these changes are mostly formatting (i.e., pre-commit).

**Comment by jukent** [comment]
The GitHub actions "Set Up Job" now has "Secret source: Actions" which it didn't before - and was part of why it wasn't accessing the secrets PAT.

**Comment by jukent** [comment]
Possibly related to this message
"""
Warning: Unexpected input(s) 'repository', valid inputs are ['token', 'path', 'add-paths', 'commit-message', 'committer', 'author', 'signoff', 'branch', 'delete-branch', 'branch-suffix', 'base', 'push-to-fork', 'title', 'body', 'labels', 'assignees', 'reviewers', 'team-reviewers', 'milestone', 'draft']
"""

**Comment by jukent** [comment]
User input looks like
'
{'action': 'opened', 'issue': {'active_lock_reason': None, 'assignee': None, 'assignees': [], 'author_association': 'NONE', 'body': '### Root Repository Name\n\nintake-cookbook\n\n### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?\n\nyes\n\n### Additional comments\n\n_No response_', 'closed_at': None, 'comments': 0, 'comments_url': 
...
'

**Comment by jukent** [comment]
I'm going to change the rightmost string in the get user submissions to be more specific. See #71

**Comment by jukent** [comment]
I'll merge this to go ahead and get all the pre-commit changes. And leave the one file out of the gitignore so that I can see if it has changed when I recreate this same PR with the issue button again

**Pull request merged**
