### PR TITLE
Add Status Badges to gallery cards

### PR DESCRIPTION
**Pull request by jukent**
Retrieving html for status badges from root repository and adding html to bottom of each gallery card. Worked with @jnmorley

### CODE REVIEW

**Review by jnmorley — APPROVED** [review]
Looks good to me.

**Comment by jukent** [comment]
There is some commented out code that will work towards grabbing the thumbnail from each repository. See https://github.com/ProjectPythiaCookbooks/cookbook-template/pull/44#event-6897327954

**Comment by brian-rose** [comment]
> Is something wrong with how I set up the GitHub actions because the deployment preview URL is empty?

I don't think those workflows will work for this repository without configuring Netlify first.

The alternative is to convert the preview actions in this repo to match what's in https://github.com/ProjectPythiaCookbooks/cookbook-template/tree/main/.github/workflows, which uses GitHub Pages for previews instead of Netlify

**Comment by jukent** [comment]
Okay I think I configured Netlify now

**Comment by clyne** [comment]
> 

Should there be a deployment URL now?

**Comment by brian-rose** [comment]
The [Actions log](https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/runs/7101476832?check_suite_focus=true#step:10:12) says:
```
Netlify credentials not provided, not deployable
```

Guidance on setting up previews with Netlify is here: https://github.com/ProjectPythia/projectpythia.github.io/tree/main/Deployment-docs
authored by @andersy005

A potentially simpler alternative for previewing PRs that are Sphinx-based in to use readthedocs.

**Comment by jukent** [comment]
Going to focus on GitHub actions in a different PR (especially because they are down right now)

**Pull request closed without merging**
