### PR TITLE
Update cookbook gallery

### LINKED ISSUE #74: Update Gallery with new Cookbook
### Root Repository Name

intake-cookbook

### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?

yes

### Additional comments

_No response_

### LINKED ISSUE #76: Update Gallery with new Cookbook
### Root Repository Name

cookbook-template

### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?

yes

### Additional comments

Test

### PR DESCRIPTION
**Pull request by jukent**
Update cookbook gallery as requested in #76. Closes #76.

### CODE REVIEW

**Comment by jukent** [comment]
Failing because of "Nonetype" tags dictionary in the cookbook's config.py

**Comment by jukent** [comment]
Change workflow to name PRs with repo name?

**Comment by jukent** [comment]
Can't have more than one open at a time currently because of using the same branch!

**Comment by jnmorley** [comment]
Thanks for catching this. It might be a good idea to add the process of updating the _config.yml file found in the template repository to the contributor's guide. I can try putting together a PR for that.

**Comment by jukent** [comment]
Oh I just did that! I wanted to add steps to use the new cookbook button, and realized that these steps were missing as well

**Comment by jnmorley** [comment]
Sounds great Thanks.

**Pull request closed without merging**
